### ISSUE TITLE
Bed leveling does not work

### ISSUE THREAD

**Issue by MaxiPaille** [abegines/ConfigMarlin118forAnycubicDeltaPlus#1]
Hey,

Thanks for your work.
I just flashed my Kossel Plus with Marlin 1.1.8 with your configuration files but it seems that bed leveling is acting weirdly.
The hot end goes up (rather than down ^^) with random motion from all the 3 steppers... (homing is working fine)
I did not investigate yet but, does it work for you ?

Thanks

**Comment by PaulGameDev** [comment]
Are you using the "Bed Leveling" (G29) command in the Prepare menu or the "Auto Leveling" (G33) under Prepare -> Delta Configuration?

**Comment by PaulGameDev** [comment]
I'd recommend to comment "#define AUTO_BED_LEVELING_BILINEAR" in the Configuration.h and use the G33 version under Delta Configuration

**Comment by LaynedIt** [comment]
Actually, you may be in the same boat as me here. What you need to do is head into configuartion.h and in endstop settings find this block of code:
`// Mechanical endstop with COM to ground and NC to Signal uses "false" here (most common setup).
#define X_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING false // set to true to invert the logic of the endstop.`
And change the `Z_MIN_ENDSTOP_INVERTING` and `Z_MIN_PROBE_ENDSTOP_INVERTING` values to `true`

**Comment by MaxiPaille** [comment]
Thanks laynedlt,
It seems to be the Z probe that is NO (normal open?) on my printer (Linear Plus V1).
It works great now.

Thanks!
